<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/** Persisted, reproducible report generated by the URL GEO scanner. */
final class UrlScanReport extends Model
{
    protected $table = 'url_scan_reports';

    protected $fillable = [
        'url',
        'normalized_url',
        'source_domain',
        'status',
        'report_json',
        'error_message',
        'error_code',
        'created_by',
        'admin_id',
        'started_at',
        'finished_at',
    ];

    protected function casts(): array
    {
        return [
            'admin_id' => 'integer',
            'started_at' => 'datetime',
            'finished_at' => 'datetime',
        ];
    }

    public function admin(): BelongsTo
    {
        return $this->belongsTo(Admin::class, 'admin_id');
    }

    /** @return array<string,mixed> */
    public function report(): array
    {
        $value = json_decode((string) $this->report_json, true);

        return is_array($value) ? $value : [];
    }
}
