<?php

return [
    'ai_workspace_manual' => [
        'name' => '桐灼GEO 后台功能与操作指南（AI 工作台专用）',
        'description' => '桐灼GEO AI 工作台用于解释后台功能、流程、原理、故障恢复和可信站内入口的系统知识。',
        'official_version' => '2026.09.10.1',
        'authoritative_locale' => 'zh_CN',
        'content_file' => 'geoflow-admin-guide.zh_CN.md',
        'content_hash' => 'dd5f1cf9dfa4b70de69bd1ad9e1411b3db0284c96709f8712572c48da6c2c552',
        'minimum_han_characters' => 10_000,
        'required_sections' => [
            '## 一、系统总览与工作方法',
            '## 二、AI 工作台',
            '## 三、数据中心与效果分析',
            '## 四、任务管理与内容生产',
            '## 五、文章管理与质量控制',
            '## 六、内容资产',
            '## 七、企业知识库与 URL 导入',
            '## 八、内容分发与托管站点',
            '## 九、人工发布与浏览器运营助手',
            '## 十、网站、主题与线索',
            '## 十一、AI 配置、模型与提示词',
            '## 十二、用户、权限、安全与审计',
            '## 十三、系统更新、部署与运行维护',
            '## 十四、API、CLI 与扩展能力',
            '## 十五、通用排查方法与回答原则',
        ],
        'required_tabs' => [
            'admin-settings',
            'ai-models',
            'ai-workspace',
            'analytics',
            'articles',
            'dashboard',
            'distribution',
            'knowledge',
            'leads',
            'manual-publications',
            'materials',
            'system-updates',
            'tasks',
        ],
    ],
];
