<?php

namespace App\Ai\Workspace\CapabilityPackages;

use App\Services\AiWorkspace\Capabilities\AdminGovernanceCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\AnalyticsDailyReportCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\AnalyticsWeeklyReportCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\ArticleDraftCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\ContentCatalogCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\ContentOpportunitiesCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\DistributionPreviewCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\DistributionPublishCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\DistributionSiteSettingsSyncCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\HostedSitePreflightCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\KnowledgeDraftCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\ManagedOperationsCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\SiteOperationsCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\SystemCapabilitiesExplainCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\TaskDraftCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\TaskStatusChangeCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\UrlImportCommitCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\UrlImportPreviewCapabilityHandler;
use App\Services\AiWorkspace\Capabilities\VisibilityDiagnoseCapabilityHandler;

final class CapabilityManifest
{
    /** @return array<string,array<string,mixed>> */
    public static function definitions(): array
    {
        return [
            'system.capabilities.explain' => [
                'name' => '系统能力说明',
                'description' => '解释 桐灼GEO 已登记能力并返回对应后台入口。',
                'maturity' => 'advisory',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'low',
                'approval_policy' => 'none',
                'version' => '1.0.0',
                'input_schema' => ['topic' => ['type' => 'string', 'required' => false, 'max' => 120]],
                'result_contract' => ['type' => 'capability_catalog'],
                'route_patterns' => ['/geo_admin?tab=dashboard', '/geo_admin?tab=ai-workspace'],
                'handler' => SystemCapabilitiesExplainCapabilityHandler::class,
            ],
            'analytics.daily_report' => [
                'name' => '运营日报',
                'description' => '汇总最近一天的内容、任务、线索与分发数据。',
                'maturity' => 'read_ready',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'low',
                'approval_policy' => 'none',
                'version' => '1.1.0',
                'input_schema' => ['date' => ['type' => 'date', 'required' => false]],
                'result_contract' => ['type' => 'operational_report'],
                'route_patterns' => ['/geo_admin?tab=analytics', '/geo_admin?tab=analytics', '/geo_admin?tab=distribution', '/geo_admin?tab=analytics'],
                'handler' => AnalyticsDailyReportCapabilityHandler::class,
            ],
            'analytics.weekly_report' => [
                'name' => '运营周报',
                'description' => '汇总最近七天趋势并给出可追溯的后台来源。',
                'maturity' => 'read_ready',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'low',
                'approval_policy' => 'none',
                'version' => '1.1.0',
                'input_schema' => ['end_date' => ['type' => 'date', 'required' => false]],
                'result_contract' => ['type' => 'operational_report'],
                'route_patterns' => ['/geo_admin?tab=analytics'],
                'handler' => AnalyticsWeeklyReportCapabilityHandler::class,
            ],
            'visibility.diagnose' => [
                'name' => 'AI 可见性诊断',
                'description' => '分析品牌或主题的 AI 可见性、信源和变化趋势。',
                'maturity' => 'read_ready',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'medium',
                'approval_policy' => 'none',
                'version' => '1.0.0',
                'input_schema' => [
                    'query' => ['type' => 'string', 'required' => true, 'max' => 200],
                    'days' => ['type' => 'integer', 'required' => false, 'min' => 1, 'max' => 90],
                ],
                'result_contract' => ['type' => 'visibility_diagnosis'],
                'route_patterns' => ['/geo_admin?tab=analytics'],
                'handler' => VisibilityDiagnoseCapabilityHandler::class,
            ],
            'content.opportunities' => [
                'name' => '内容机会分析',
                'description' => '结合内容、关键词和线索数据识别高价值选题。',
                'maturity' => 'read_ready',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'medium',
                'approval_policy' => 'none',
                'version' => '1.0.0',
                'input_schema' => ['theme' => ['type' => 'string', 'required' => false, 'max' => 200]],
                'result_contract' => ['type' => 'content_opportunities'],
                'route_patterns' => [
                    '/geo_admin?tab=analytics', '/geo_admin?tab=articles', '/geo_admin?tab=materials',
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=leads', '/geo_admin?tab=leads',
                ],
                'handler' => ContentOpportunitiesCapabilityHandler::class,
            ],
            'task.draft' => [
                'name' => '任务草稿',
                'description' => '创建暂停状态的任务草稿，保留原有任务配置入口。',
                'maturity' => 'draft_ready',
                'risk' => 'medium',
                'permission' => 'admin',
                'execution_scope' => 'internal_write',
                'data_classification' => 'internal',
                'cost' => 'low',
                'approval_policy' => 'once',
                'version' => '1.1.0',
                'input_schema' => [
                    'name' => ['type' => 'string', 'required' => true, 'max' => 100],
                    'article_limit' => ['type' => 'integer', 'required' => false, 'min' => 1, 'max' => 100],
                    'publish_interval' => ['type' => 'integer', 'required' => false, 'min' => 60, 'max' => 2592000],
                ],
                'result_contract' => ['type' => 'task_draft', 'payload_schema' => ['task_id' => 'integer', 'status' => 'string']],
                'route_patterns' => ['/geo_admin?tab=tasks', '/geo_admin?tab=tasks', '/geo_admin?tab=tasks', '/geo_admin?tab=tasks'],
                'handler' => TaskDraftCapabilityHandler::class,
            ],
            'article.draft' => [
                'name' => '文章草稿',
                'description' => '创建待审核文章草稿并继续执行原有风险扫描。',
                'maturity' => 'draft_ready',
                'risk' => 'medium',
                'permission' => 'admin',
                'execution_scope' => 'internal_write',
                'data_classification' => 'internal',
                'cost' => 'medium',
                'approval_policy' => 'once',
                'version' => '1.1.0',
                'input_schema' => [
                    'title' => ['type' => 'string', 'required' => true, 'max' => 500],
                    'content' => ['type' => 'string', 'required' => true, 'max' => 200000],
                    'category_id' => ['type' => 'integer', 'required' => true, 'min' => 1],
                    'author_id' => ['type' => 'integer', 'required' => true, 'min' => 1],
                ],
                'result_contract' => ['type' => 'article_draft', 'payload_schema' => ['article_id' => 'integer', 'status' => 'string', 'review_status' => 'string']],
                'route_patterns' => ['/geo_admin?tab=articles', '/geo_admin?tab=articles', '/geo_admin?tab=articles', '/geo_admin?tab=articles'],
                'handler' => ArticleDraftCapabilityHandler::class,
            ],
            'knowledge.draft' => [
                'name' => '知识草稿',
                'description' => '创建企业知识工程草稿，后续沿用原有校验与发布流程。',
                'maturity' => 'draft_ready',
                'risk' => 'medium',
                'permission' => 'admin',
                'execution_scope' => 'internal_write',
                'data_classification' => 'confidential',
                'cost' => 'medium',
                'approval_policy' => 'once',
                'version' => '1.1.0',
                'input_schema' => [
                    'name' => ['type' => 'string', 'required' => true, 'max' => 120],
                    'description' => ['type' => 'string', 'required' => false, 'max' => 2000],
                    'content' => ['type' => 'string', 'required' => true, 'max' => 500000],
                ],
                'result_contract' => ['type' => 'knowledge_draft', 'payload_schema' => ['project_id' => 'integer', 'status' => 'string']],
                'route_patterns' => [
                    '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge',
                    '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge',
                    '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge',
                ],
                'handler' => KnowledgeDraftCapabilityHandler::class,
            ],
            'url_import.preview' => [
                'name' => 'URL 导入预览',
                'description' => '校验 URL 与导入选项，只生成预览计划。',
                'maturity' => 'draft_ready',
                'risk' => 'medium',
                'permission' => 'super_admin',
                'execution_scope' => 'external_read',
                'data_classification' => 'public',
                'cost' => 'medium',
                'approval_policy' => 'once',
                'version' => '1.2.0',
                'input_schema' => ['url' => ['type' => 'url', 'required' => true, 'max' => 2048]],
                'result_contract' => ['type' => 'url_import_preview', 'payload_schema' => ['job_id' => 'integer', 'url' => 'string']],
                'route_patterns' => [
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                ],
                'handler' => UrlImportPreviewCapabilityHandler::class,
            ],
            'url_import.commit' => [
                'name' => 'URL 导入提交',
                'description' => '将已完成的 URL 预览结果写入知识库、关键词库和标题库。',
                'maturity' => 'execute_ready',
                'risk' => 'high',
                'permission' => 'super_admin',
                'execution_scope' => 'internal_write',
                'data_classification' => 'confidential',
                'cost' => 'low',
                'approval_policy' => 'per_step',
                'version' => '1.0.0',
                'input_schema' => ['job_id' => ['type' => 'integer', 'required' => true, 'min' => 1]],
                'result_contract' => ['type' => 'url_import_commit'],
                'route_patterns' => ['/geo_admin?tab=materials'],
                'handler' => UrlImportCommitCapabilityHandler::class,
            ],
            'distribution.preview' => [
                'name' => '分发预览',
                'description' => '生成文章与目标站点矩阵，不发送外部请求。',
                'maturity' => 'draft_ready',
                'risk' => 'medium',
                'permission' => 'super_admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'confidential',
                'cost' => 'low',
                'approval_policy' => 'once',
                'version' => '1.0.0',
                'input_schema' => [
                    'article_ids' => ['type' => 'integer_list', 'required' => true, 'min_items' => 1, 'max_items' => 100],
                    'channel_ids' => ['type' => 'integer_list', 'required' => true, 'min_items' => 1, 'max_items' => 100],
                ],
                'result_contract' => ['type' => 'distribution_matrix'],
                'route_patterns' => [
                    '/geo_admin?tab=distribution', '/geo_admin?tab=distribution', '/geo_admin?tab=distribution',
                    '/geo_admin?tab=distribution', '/geo_admin?tab=distribution',
                    '/geo_admin?tab=distribution',
                ],
                'handler' => DistributionPreviewCapabilityHandler::class,
            ],
            'task.status.change' => [
                'name' => '任务启停',
                'description' => '通过现有任务生命周期服务启用或暂停任务。',
                'maturity' => 'execute_ready',
                'risk' => 'high',
                'permission' => 'admin',
                'execution_scope' => 'internal_write',
                'data_classification' => 'internal',
                'cost' => 'low',
                'approval_policy' => 'per_step',
                'version' => '1.0.0',
                'input_schema' => [
                    'task_id' => ['type' => 'integer', 'required' => true, 'min' => 1],
                    'action' => ['type' => 'enum', 'required' => true, 'values' => ['start', 'stop']],
                ],
                'result_contract' => ['type' => 'task_state'],
                'route_patterns' => ['/geo_admin?tab=tasks', '/geo_admin?tab=tasks'],
                'handler' => TaskStatusChangeCapabilityHandler::class,
            ],
            'distribution.publish' => [
                'name' => '多站分发入队',
                'description' => '按已审批的文章与站点矩阵进入现有分发队列，保留任务默认分发配置，远程结果由分发中心对账。',
                'maturity' => 'execute_ready',
                'risk' => 'high',
                'permission' => 'super_admin',
                'execution_scope' => 'external_write',
                'data_classification' => 'confidential',
                'cost' => 'high',
                'approval_policy' => 'target_matrix',
                'version' => '1.4.0',
                'input_schema' => [
                    'article_ids' => ['type' => 'integer_list', 'required' => true, 'min_items' => 1, 'max_items' => 100],
                    'channel_ids' => ['type' => 'integer_list', 'required' => true, 'min_items' => 1, 'max_items' => 100],
                ],
                'result_contract' => ['type' => 'distribution_enqueue'],
                'route_patterns' => ['/geo_admin?tab=distribution', '/geo_admin?tab=distribution'],
                'handler' => DistributionPublishCapabilityHandler::class,
            ],
            'distribution.site_settings_sync' => [
                'name' => '站点设置同步',
                'description' => '按目标站点拆分外部同步步骤，复用现有操作租约和内容刷新队列。',
                'maturity' => 'execute_ready',
                'risk' => 'high',
                'permission' => 'super_admin',
                'execution_scope' => 'external_write',
                'data_classification' => 'confidential',
                'cost' => 'high',
                'approval_policy' => 'target_matrix',
                'version' => '1.1.0',
                'input_schema' => [
                    'channel_ids' => ['type' => 'integer_list', 'required' => true, 'min_items' => 1, 'max_items' => 50],
                ],
                'result_contract' => ['type' => 'site_settings_sync'],
                'route_patterns' => [
                    '/geo_admin?tab=distribution', '/geo_admin?tab=distribution',
                    '/geo_admin?tab=distribution',
                ],
                'handler' => DistributionSiteSettingsSyncCapabilityHandler::class,
            ],
            'hosted_site.preflight' => [
                'name' => '托管站点预检',
                'description' => '对指定托管站点执行连接与配置预检。',
                'maturity' => 'execute_ready',
                'risk' => 'medium',
                'permission' => 'super_admin',
                'execution_scope' => 'external_read',
                'data_classification' => 'confidential',
                'cost' => 'medium',
                'approval_policy' => 'per_step',
                'version' => '1.1.0',
                'input_schema' => ['hosted_site_id' => ['type' => 'integer', 'required' => true, 'min' => 1]],
                'result_contract' => ['type' => 'hosted_site_preflight'],
                'route_patterns' => [
                    '/geo_admin?tab=distribution', '/geo_admin?tab=distribution',
                    '/geo_admin?tab=distribution',
                ],
                'handler' => HostedSitePreflightCapabilityHandler::class,
            ],
            'admin.governance' => [
                'name' => '管理与安全配置',
                'description' => '可解释入口和权限要求，不允许 AI 执行。',
                'maturity' => 'restricted',
                'risk' => 'critical',
                'permission' => 'super_admin',
                'execution_scope' => 'none',
                'data_classification' => 'restricted',
                'cost' => 'none',
                'approval_policy' => 'blocked',
                'version' => '1.0.0',
                'input_schema' => [],
                'result_contract' => ['type' => 'navigation_only'],
                'route_patterns' => [
                    '/geo_admin?tab=system-updates', '/geo_admin?tab=admin-settings', '/geo_admin?tab=admin-settings',
                    '/geo_admin?tab=admin-settings', '/geo_admin?tab=admin-settings', '/geo_admin?tab=ai-models',
                    '/geo_admin?tab=ai-models', '/geo_admin?tab=ai-models', '/geo_admin?tab=ai-models',
                    '/geo_admin?tab=ai-models', '/geo_admin?tab=ai-models', '/geo_admin?tab=ai-models',
                ],
                'handler' => AdminGovernanceCapabilityHandler::class,
            ],
            'managed.operations' => [
                'name' => '受控后台操作',
                'description' => '覆盖尚未开放给 AI 执行的内容、分发和站点写操作。',
                'maturity' => 'restricted',
                'risk' => 'critical',
                'permission' => 'admin',
                'execution_scope' => 'none',
                'data_classification' => 'restricted',
                'cost' => 'none',
                'approval_policy' => 'blocked',
                'version' => '1.0.0',
                'input_schema' => [],
                'result_contract' => ['type' => 'navigation_only'],
                'route_patterns' => [
                    '/geo_admin?tab=articles', '/geo_admin?tab=tasks', '/geo_admin?tab=knowledge', '/geo_admin?tab=knowledge',
                    '/geo_admin?tab=materials', '/geo_admin?tab=distribution', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=manual-publications', '/geo_admin?tab=leads', '/geo_admin?tab=leads', '/geo_admin?tab=admin-settings',
                ],
                'handler' => ManagedOperationsCapabilityHandler::class,
            ],
            'content.catalog' => [
                'name' => '内容与素材目录',
                'description' => '解释内容、素材、分类、作者、标题和关键词管理入口。',
                'maturity' => 'advisory',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'none',
                'approval_policy' => 'none',
                'version' => '1.0.0',
                'input_schema' => [],
                'result_contract' => ['type' => 'navigation_only'],
                'route_patterns' => [
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=materials', '/geo_admin?tab=materials', '/geo_admin?tab=materials',
                    '/geo_admin?tab=materials', '/geo_admin?tab=manual-publications', '/geo_admin?tab=manual-publications',
                    '/geo_admin?tab=manual-publications', '/geo_admin?tab=manual-publications',
                ],
                'handler' => ContentCatalogCapabilityHandler::class,
            ],
            'site.operations' => [
                'name' => '站点运营目录',
                'description' => '解释站点设置、表单、线索与主题相关入口。',
                'maturity' => 'advisory',
                'risk' => 'low',
                'permission' => 'admin',
                'execution_scope' => 'internal_read',
                'data_classification' => 'internal',
                'cost' => 'none',
                'approval_policy' => 'none',
                'version' => '1.0.0',
                'input_schema' => [],
                'result_contract' => ['type' => 'navigation_only'],
                'route_patterns' => [
                    '/geo_admin?tab=admin-settings', '/geo_admin?tab=admin-settings',
                    '/geo_admin?tab=admin-settings', '/geo_admin?tab=admin-settings',
                    '/geo_admin?tab=admin-settings', '/geo_admin?tab=admin-settings',
                    '/geo_admin?tab=leads', '/geo_admin?tab=leads', '/geo_admin?tab=leads',
                ],
                'handler' => SiteOperationsCapabilityHandler::class,
            ],

        ];
    }
}
